//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATAPY.Document.Data.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATAPY.Document.Data.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Than One Table On Page.
        /// </summary>
        internal static string ALLOW_MULTIPLE_TABLES_ON_PAGE {
            get {
                return ResourceManager.GetString("ALLOW_MULTIPLE_TABLES_ON_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows cases when several table instances occurs within one page..
        /// </summary>
        internal static string ALLOW_MULTIPLE_TABLES_ON_PAGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("ALLOW_MULTIPLE_TABLES_ON_PAGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Properties.
        /// </summary>
        internal static string CATEGORY_BASIC {
            get {
                return ResourceManager.GetString("CATEGORY_BASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Page.
        /// </summary>
        internal static string END_PAGE {
            get {
                return ResourceManager.GetString("END_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index where multipage table ends.
        ///-1 - last page of a document..
        /// </summary>
        internal static string END_PAGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("END_PAGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Extra Column Split.
        /// </summary>
        internal static string EXTRA_COLUMNS_SPLIT {
            get {
                return ResourceManager.GetString("EXTRA_COLUMNS_SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables extra column split for cases, when header has no enought white gape, but table data has..
        /// </summary>
        internal static string EXTRA_COLUMNS_SPLIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXTRA_COLUMNS_SPLIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Columns Split Indices.
        /// </summary>
        internal static string EXTRA_COLUMNS_SPLIT_INDICES {
            get {
                return ResourceManager.GetString("EXTRA_COLUMNS_SPLIT_INDICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indices of table columns that needs to be extra splitted..
        /// </summary>
        internal static string EXTRA_COLUMNS_SPLIT_INDICES_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXTRA_COLUMNS_SPLIT_INDICES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtration Rule(s).
        /// </summary>
        internal static string FILTRATION_RULES {
            get {
                return ResourceManager.GetString("FILTRATION_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression based rules, specifying lines dropped out of the table..
        /// </summary>
        internal static string FILTRATION_RULES_DESCRIPTION {
            get {
                return ResourceManager.GetString("FILTRATION_RULES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Rule(s).
        /// </summary>
        internal static string FOOTER_RULE {
            get {
                return ResourceManager.GetString("FOOTER_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression based rule, specifying first line of page footer that sould be dropped out..
        /// </summary>
        internal static string FOOTER_RULE_DESCRIPTION {
            get {
                return ResourceManager.GetString("FOOTER_RULE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Search Rule(s).
        /// </summary>
        internal static string HEADER_RULES {
            get {
                return ResourceManager.GetString("HEADER_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of regular expression set of rules, specifying search table header string(s)..
        /// </summary>
        internal static string HEADER_RULES_DESCRIPTION {
            get {
                return ResourceManager.GetString("HEADER_RULES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Column Cell Alignment.
        /// </summary>
        internal static string MASTER_COLUMN_CELL_ALIGNMENT {
            get {
                return ResourceManager.GetString("MASTER_COLUMN_CELL_ALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical content alignment in master column cells..
        /// </summary>
        internal static string MASTER_COLUMN_CELL_ALIGNMENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("MASTER_COLUMN_CELL_ALIGNMENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Column Index.
        /// </summary>
        internal static string MASTER_COLUMN_INDEX {
            get {
                return ResourceManager.GetString("MASTER_COLUMN_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-based index of table column, that identify number of rows in table..
        /// </summary>
        internal static string MASTER_COLUMN_INDEX_DESCRIPTION {
            get {
                return ResourceManager.GetString("MASTER_COLUMN_INDEX_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows are equal to strings count.
        /// </summary>
        internal static string MAX_STRINGS_COUNT {
            get {
                return ResourceManager.GetString("MAX_STRINGS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum White Gape Factor.
        /// </summary>
        internal static string MIN_WHITE_GAPE_FACTOR {
            get {
                return ResourceManager.GetString("MIN_WHITE_GAPE_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum white space factor that needs to be preserved on table text analysis to split into columns.
        ///Gape is set as multiply to average symbol width of an analyzed string..
        /// </summary>
        internal static string MIN_WHITE_GAPE_FACTOR_DESCRIPTION {
            get {
                return ResourceManager.GetString("MIN_WHITE_GAPE_FACTOR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multipage Table.
        /// </summary>
        internal static string MULTIPAGE_TABLE {
            get {
                return ResourceManager.GetString("MULTIPAGE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this option means that table can start on one page of document and continues on other pages..
        /// </summary>
        internal static string MULTIPAGE_TABLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("MULTIPAGE_TABLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohibit Unnamed Columns.
        /// </summary>
        internal static string PROHIBIT_UNNAMED_COLUMNS {
            get {
                return ResourceManager.GetString("PROHIBIT_UNNAMED_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohibit table analysis from making columns with no header text..
        /// </summary>
        internal static string PROHIBIT_UNNAMED_COLUMNS_DESCRIPTION {
            get {
                return ResourceManager.GetString("PROHIBIT_UNNAMED_COLUMNS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Split Rule.
        /// </summary>
        internal static string ROWS_SPLIT_RULE {
            get {
                return ResourceManager.GetString("ROWS_SPLIT_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option that specify how table data should be split to rows..
        /// </summary>
        internal static string ROWS_SPLIT_RULE_DESCRIPTION {
            get {
                return ResourceManager.GetString("ROWS_SPLIT_RULE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        internal static string START_PAGE {
            get {
                return ResourceManager.GetString("START_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index where multipage table started..
        /// </summary>
        internal static string START_PAGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("START_PAGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Line Rule.
        /// </summary>
        internal static string STOP_RULE {
            get {
                return ResourceManager.GetString("STOP_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression based rule, specifying first line below the table..
        /// </summary>
        internal static string STOP_RULE_DESCRIPTION {
            get {
                return ResourceManager.GetString("STOP_RULE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Search Settings.
        /// </summary>
        internal static string TABLE_SEARCH_SETTINGS {
            get {
                return ResourceManager.GetString("TABLE_SEARCH_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed Columns Join Direction.
        /// </summary>
        internal static string UNNAMED_COLUMNS_MERGE_DIRECTION {
            get {
                return ResourceManager.GetString("UNNAMED_COLUMNS_MERGE_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction to which unnamed columns (when found) will be joined to..
        /// </summary>
        internal static string UNNAMED_COLUMNS_MERGE_DIRECTION_DESCRIPTION {
            get {
                return ResourceManager.GetString("UNNAMED_COLUMNS_MERGE_DIRECTION_DESCRIPTION", resourceCulture);
            }
        }
    }
}
